// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenMenu
void ui_ScreenMenu_screen_init(void);
extern lv_obj_t *ui_ScreenMenu;
void ui_event_ButtonRGB( lv_event_t * e);
extern lv_obj_t *ui_ButtonRGB;
extern lv_obj_t *ui_LabelConfig;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_LabelTask1;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_LabelTask;
void ui_event_ButtonArm( lv_event_t * e);
extern lv_obj_t *ui_ButtonArm;
extern lv_obj_t *ui_LabelArm;
// SCREEN: ui_ScreenCFIG
void ui_ScreenCFIG_screen_init(void);
extern lv_obj_t *ui_ScreenCFIG;
void ui_event_ButtonReturn2( lv_event_t * e);
extern lv_obj_t *ui_ButtonReturn2;
extern lv_obj_t *ui_LabelReturn2;
void ui_event_ButtonWrite( lv_event_t * e);
extern lv_obj_t *ui_ButtonWrite;
extern lv_obj_t *ui_LabelConfirm1;
void ui_event_ButtonRead( lv_event_t * e);
extern lv_obj_t *ui_ButtonRead;
extern lv_obj_t *ui_LabelConfirm2;
void ui_event_ButtonBTN4( lv_event_t * e);
extern lv_obj_t *ui_ButtonBTN4;
extern lv_obj_t *ui_LabelConfirm3;
void ui_event_ButtonBTN3( lv_event_t * e);
extern lv_obj_t *ui_ButtonBTN3;
extern lv_obj_t *ui_LabelConfirm4;
void ui_event_ButtonBTN2( lv_event_t * e);
extern lv_obj_t *ui_ButtonBTN2;
extern lv_obj_t *ui_LabelConfirm5;
void ui_event_ButtonBTN1( lv_event_t * e);
extern lv_obj_t *ui_ButtonBTN1;
extern lv_obj_t *ui_LabelConfirm6;
void ui_event_TextAreaOV( lv_event_t * e);
extern lv_obj_t *ui_TextAreaOV;
void ui_event_ButtonBTNSwitch( lv_event_t * e);
extern lv_obj_t *ui_ButtonBTNSwitch;
extern lv_obj_t *ui_LabelConfirm7;
void ui_event_KeyboardOV( lv_event_t * e);
extern lv_obj_t *ui_KeyboardOV;
// SCREEN: ui_ScreenArm
void ui_ScreenArm_screen_init(void);
extern lv_obj_t *ui_ScreenArm;
void ui_event_ButtonReturn1( lv_event_t * e);
extern lv_obj_t *ui_ButtonReturn1;
extern lv_obj_t *ui_LabelReturn1;
void ui_event_ButtonConfirm( lv_event_t * e);
extern lv_obj_t *ui_ButtonConfirm;
extern lv_obj_t *ui_LabelConfirm;
extern lv_obj_t *ui_DropdownHolder;
void ui_event_TextAreaArmX( lv_event_t * e);
extern lv_obj_t *ui_TextAreaArmX;
void ui_event_TextAreaArmY( lv_event_t * e);
extern lv_obj_t *ui_TextAreaArmY;
void ui_event_TextAreaArmZ( lv_event_t * e);
extern lv_obj_t *ui_TextAreaArmZ;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_SwitchArmTong;
extern lv_obj_t *ui_LabelTong;
void ui_event_KeyboardArm( lv_event_t * e);
extern lv_obj_t *ui_KeyboardArm;
// SCREEN: ui_ScreenTask
void ui_ScreenTask_screen_init(void);
extern lv_obj_t *ui_ScreenTask;
void ui_event_ButtonReturn3( lv_event_t * e);
extern lv_obj_t *ui_ButtonReturn3;
extern lv_obj_t *ui_LabelReturn3;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_LabelTaskNum;
void ui_event_ButtonTaskRun( lv_event_t * e);
extern lv_obj_t *ui_ButtonTaskRun;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_LabelFinishTime;
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
void ui_event_ButtonReturn4( lv_event_t * e);
extern lv_obj_t *ui_ButtonReturn4;
extern lv_obj_t *ui_LabelReturn4;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui____initial_actions0;



LV_FONT_DECLARE( ui_font_bigNum);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
