// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void TaskReady(lv_event_t * e)
{
	// Your code here
}

void ArmSetConfirm(lv_event_t * e)
{
	// Your code here
}

void KeyBoardCancel(lv_event_t * e)
{
	// Your code here
}

void SetKeyBoard(lv_event_t * e)
{
	// Your code here
}

void ButtonTaskRun(lv_event_t * e)
{
	// Your code here
}

void TestArmConfirm(lv_event_t * e)
{
	// Your code here
}

void CfigConfirm(lv_event_t * e)
{
	// Your code here
}

void TestOpenmvConfirm(lv_event_t * e)
{
	// Your code here
}

void SetHighTaskPriority(lv_event_t * e)
{
	// Your code here
}

void SetLowTaskPriority(lv_event_t * e)
{
	// Your code here
}

void EventOvWrite(lv_event_t * e)
{
	// Your code here
}

void EventOvRead(lv_event_t * e)
{
	// Your code here
}

void EventBTN4(lv_event_t * e)
{
	// Your code here
}

void EventBTN3(lv_event_t * e)
{
	// Your code here
}

void EventBTN2(lv_event_t * e)
{
	// Your code here
}

void EventBTN1(lv_event_t * e)
{
	// Your code here
}

void EventBTNSwitch(lv_event_t * e)
{
	// Your code here
}
