// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenCFIG_screen_init(void)
{
ui_ScreenCFIG = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenCFIG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ButtonReturn2 = lv_btn_create(ui_ScreenCFIG);
lv_obj_set_width( ui_ButtonReturn2, lv_pct(15));
lv_obj_set_height( ui_ButtonReturn2, lv_pct(10));
lv_obj_add_flag( ui_ButtonReturn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonReturn2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonReturn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonReturn2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelReturn2 = lv_label_create(ui_ButtonReturn2);
lv_obj_set_width( ui_LabelReturn2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelReturn2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelReturn2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelReturn2,"<--");
lv_obj_set_style_text_color(ui_LabelReturn2, lv_color_hex(0x100F0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelReturn2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonWrite = lv_btn_create(ui_ScreenCFIG);
lv_obj_set_width( ui_ButtonWrite, lv_pct(20));
lv_obj_set_height( ui_ButtonWrite, lv_pct(15));
lv_obj_set_x( ui_ButtonWrite, lv_pct(30) );
lv_obj_set_y( ui_ButtonWrite, lv_pct(-65) );
lv_obj_set_align( ui_ButtonWrite, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_ButtonWrite, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonWrite, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonWrite, lv_color_hex(0xEB1212), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_ButtonWrite, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_LabelConfirm1 = lv_label_create(ui_ButtonWrite);
lv_obj_set_width( ui_LabelConfirm1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelConfirm1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelConfirm1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelConfirm1,"Write");

ui_ButtonRead = lv_btn_create(ui_ScreenCFIG);
lv_obj_set_width( ui_ButtonRead, lv_pct(20));
lv_obj_set_height( ui_ButtonRead, lv_pct(15));
lv_obj_set_x( ui_ButtonRead, lv_pct(-30) );
lv_obj_set_y( ui_ButtonRead, lv_pct(-65) );
lv_obj_set_align( ui_ButtonRead, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_ButtonRead, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonRead, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonRead, lv_color_hex(0xEB1212), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_ButtonRead, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_LabelConfirm2 = lv_label_create(ui_ButtonRead);
lv_obj_set_width( ui_LabelConfirm2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelConfirm2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelConfirm2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelConfirm2,"Read");

ui_ButtonBTN4 = lv_btn_create(ui_ScreenCFIG);
lv_obj_set_width( ui_ButtonBTN4, lv_pct(20));
lv_obj_set_height( ui_ButtonBTN4, lv_pct(15));
lv_obj_set_x( ui_ButtonBTN4, lv_pct(30) );
lv_obj_set_y( ui_ButtonBTN4, lv_pct(40) );
lv_obj_set_align( ui_ButtonBTN4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBTN4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBTN4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonBTN4, lv_color_hex(0xEB1212), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_ButtonBTN4, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_LabelConfirm3 = lv_label_create(ui_ButtonBTN4);
lv_obj_set_width( ui_LabelConfirm3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelConfirm3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelConfirm3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelConfirm3,"BTN4");

ui_ButtonBTN3 = lv_btn_create(ui_ScreenCFIG);
lv_obj_set_width( ui_ButtonBTN3, lv_pct(20));
lv_obj_set_height( ui_ButtonBTN3, lv_pct(15));
lv_obj_set_x( ui_ButtonBTN3, lv_pct(-30) );
lv_obj_set_y( ui_ButtonBTN3, lv_pct(40) );
lv_obj_set_align( ui_ButtonBTN3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBTN3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBTN3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonBTN3, lv_color_hex(0xEB1212), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_ButtonBTN3, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_LabelConfirm4 = lv_label_create(ui_ButtonBTN3);
lv_obj_set_width( ui_LabelConfirm4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelConfirm4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelConfirm4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelConfirm4,"BTN3");

ui_ButtonBTN2 = lv_btn_create(ui_ScreenCFIG);
lv_obj_set_width( ui_ButtonBTN2, lv_pct(20));
lv_obj_set_height( ui_ButtonBTN2, lv_pct(15));
lv_obj_set_x( ui_ButtonBTN2, lv_pct(30) );
lv_obj_set_y( ui_ButtonBTN2, lv_pct(10) );
lv_obj_set_align( ui_ButtonBTN2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBTN2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBTN2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonBTN2, lv_color_hex(0xEB1212), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_ButtonBTN2, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_LabelConfirm5 = lv_label_create(ui_ButtonBTN2);
lv_obj_set_width( ui_LabelConfirm5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelConfirm5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelConfirm5, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelConfirm5,"BTN2");

ui_ButtonBTN1 = lv_btn_create(ui_ScreenCFIG);
lv_obj_set_width( ui_ButtonBTN1, lv_pct(20));
lv_obj_set_height( ui_ButtonBTN1, lv_pct(15));
lv_obj_set_x( ui_ButtonBTN1, lv_pct(-30) );
lv_obj_set_y( ui_ButtonBTN1, lv_pct(10) );
lv_obj_set_align( ui_ButtonBTN1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBTN1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBTN1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonBTN1, lv_color_hex(0xEB1212), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_ButtonBTN1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_LabelConfirm6 = lv_label_create(ui_ButtonBTN1);
lv_obj_set_width( ui_LabelConfirm6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelConfirm6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelConfirm6, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelConfirm6,"BTN1");

ui_TextAreaOV = lv_textarea_create(ui_ScreenCFIG);
lv_obj_set_width( ui_TextAreaOV, 65);
lv_obj_set_height( ui_TextAreaOV, LV_SIZE_CONTENT);   /// 15
lv_obj_set_x( ui_TextAreaOV, lv_pct(0) );
lv_obj_set_y( ui_TextAreaOV, lv_pct(-65) );
lv_obj_set_align( ui_TextAreaOV, LV_ALIGN_BOTTOM_MID );
if ("-0123456789.*"=="") lv_textarea_set_accepted_chars(ui_TextAreaOV, NULL);
else lv_textarea_set_accepted_chars(ui_TextAreaOV, "-0123456789.*");
lv_textarea_set_max_length(ui_TextAreaOV,8);
lv_textarea_set_placeholder_text(ui_TextAreaOV,"num");
lv_textarea_set_one_line(ui_TextAreaOV,true);



ui_ButtonBTNSwitch = lv_btn_create(ui_ScreenCFIG);
lv_obj_set_width( ui_ButtonBTNSwitch, lv_pct(20));
lv_obj_set_height( ui_ButtonBTNSwitch, lv_pct(15));
lv_obj_set_x( ui_ButtonBTNSwitch, lv_pct(0) );
lv_obj_set_y( ui_ButtonBTNSwitch, lv_pct(25) );
lv_obj_set_align( ui_ButtonBTNSwitch, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonBTNSwitch, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonBTNSwitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonBTNSwitch, lv_color_hex(0xEB1212), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_ButtonBTNSwitch, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_LabelConfirm7 = lv_label_create(ui_ButtonBTNSwitch);
lv_obj_set_width( ui_LabelConfirm7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelConfirm7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelConfirm7, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelConfirm7,"ON/OFF");

ui_KeyboardOV = lv_keyboard_create(ui_ScreenCFIG);
lv_keyboard_set_mode(ui_KeyboardOV,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_KeyboardOV, lv_pct(100));
lv_obj_set_height( ui_KeyboardOV, lv_pct(60));
lv_obj_set_align( ui_KeyboardOV, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_KeyboardOV, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_add_event_cb(ui_ButtonReturn2, ui_event_ButtonReturn2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonWrite, ui_event_ButtonWrite, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonRead, ui_event_ButtonRead, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonBTN4, ui_event_ButtonBTN4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonBTN3, ui_event_ButtonBTN3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonBTN2, ui_event_ButtonBTN2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonBTN1, ui_event_ButtonBTN1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaOV, ui_event_TextAreaOV, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonBTNSwitch, ui_event_ButtonBTNSwitch, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_KeyboardOV,ui_TextAreaOV);
lv_obj_add_event_cb(ui_KeyboardOV, ui_event_KeyboardOV, LV_EVENT_ALL, NULL);

}
