// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenRGB_screen_init(void)
{
ui_ScreenRGB = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenRGB, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Colorwheel2 = lv_colorwheel_create(ui_ScreenRGB,true);
lv_obj_set_width( ui_Colorwheel2, 150);
lv_obj_set_height( ui_Colorwheel2, 150);
lv_obj_set_align( ui_Colorwheel2, LV_ALIGN_CENTER );

ui_ButtonReturn2 = lv_btn_create(ui_ScreenRGB);
lv_obj_set_width( ui_ButtonReturn2, lv_pct(15));
lv_obj_set_height( ui_ButtonReturn2, lv_pct(10));
lv_obj_add_flag( ui_ButtonReturn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonReturn2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonReturn2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonReturn2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelReturn2 = lv_label_create(ui_ButtonReturn2);
lv_obj_set_width( ui_LabelReturn2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelReturn2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelReturn2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelReturn2,"<--");
lv_obj_set_style_text_color(ui_LabelReturn2, lv_color_hex(0x100F0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelReturn2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Colorwheel2, ui_event_Colorwheel2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonReturn2, ui_event_ButtonReturn2, LV_EVENT_ALL, NULL);

}
