// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenMenu_screen_init(void)
{
ui_ScreenMenu = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenMenu, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ButtonRGB = lv_btn_create(ui_ScreenMenu);
lv_obj_set_width( ui_ButtonRGB, lv_pct(49));
lv_obj_set_height( ui_ButtonRGB, lv_pct(49));
lv_obj_add_flag( ui_ButtonRGB, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonRGB, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonRGB, lv_color_hex(0xE1D118), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonRGB, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelConfig = lv_label_create(ui_ButtonRGB);
lv_obj_set_width( ui_LabelConfig, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelConfig, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelConfig, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelConfig,"CFIG");
lv_obj_set_style_text_font(ui_LabelConfig, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2 = lv_btn_create(ui_ScreenMenu);
lv_obj_set_width( ui_Button2, lv_pct(49));
lv_obj_set_height( ui_Button2, lv_pct(49));
lv_obj_set_align( ui_Button2, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x24D844), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelTask1 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_LabelTask1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTask1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelTask1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTask1,"INFOR");
lv_obj_set_style_text_font(ui_LabelTask1, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button3 = lv_btn_create(ui_ScreenMenu);
lv_obj_set_width( ui_Button3, lv_pct(49));
lv_obj_set_height( ui_Button3, lv_pct(49));
lv_obj_set_align( ui_Button3, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xD42B39), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelTask = lv_label_create(ui_Button3);
lv_obj_set_width( ui_LabelTask, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTask, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelTask, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTask,"TASK");
lv_obj_set_style_text_font(ui_LabelTask, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonArm = lv_btn_create(ui_ScreenMenu);
lv_obj_set_width( ui_ButtonArm, lv_pct(49));
lv_obj_set_height( ui_ButtonArm, lv_pct(49));
lv_obj_set_align( ui_ButtonArm, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_ButtonArm, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonArm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelArm = lv_label_create(ui_ButtonArm);
lv_obj_set_width( ui_LabelArm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelArm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelArm, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelArm,"ARM");
lv_obj_set_style_text_font(ui_LabelArm, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ButtonRGB, ui_event_ButtonRGB, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonArm, ui_event_ButtonArm, LV_EVENT_ALL, NULL);

}
