// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScreenMenu
void ui_ScreenMenu_screen_init(void);
lv_obj_t *ui_ScreenMenu;
void ui_event_ButtonRGB( lv_event_t * e);
lv_obj_t *ui_ButtonRGB;
lv_obj_t *ui_LabelConfig;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_LabelTask1;
void ui_event_Button3( lv_event_t * e);
lv_obj_t *ui_Button3;
lv_obj_t *ui_LabelTask;
void ui_event_ButtonArm( lv_event_t * e);
lv_obj_t *ui_ButtonArm;
lv_obj_t *ui_LabelArm;


// SCREEN: ui_ScreenCFIG
void ui_ScreenCFIG_screen_init(void);
lv_obj_t *ui_ScreenCFIG;
void ui_event_ButtonReturn2( lv_event_t * e);
lv_obj_t *ui_ButtonReturn2;
lv_obj_t *ui_LabelReturn2;
void ui_event_ButtonWrite( lv_event_t * e);
lv_obj_t *ui_ButtonWrite;
lv_obj_t *ui_LabelConfirm1;
void ui_event_ButtonRead( lv_event_t * e);
lv_obj_t *ui_ButtonRead;
lv_obj_t *ui_LabelConfirm2;
void ui_event_ButtonBTN4( lv_event_t * e);
lv_obj_t *ui_ButtonBTN4;
lv_obj_t *ui_LabelConfirm3;
void ui_event_ButtonBTN3( lv_event_t * e);
lv_obj_t *ui_ButtonBTN3;
lv_obj_t *ui_LabelConfirm4;
void ui_event_ButtonBTN2( lv_event_t * e);
lv_obj_t *ui_ButtonBTN2;
lv_obj_t *ui_LabelConfirm5;
void ui_event_ButtonBTN1( lv_event_t * e);
lv_obj_t *ui_ButtonBTN1;
lv_obj_t *ui_LabelConfirm6;
void ui_event_TextAreaOV( lv_event_t * e);
lv_obj_t *ui_TextAreaOV;
void ui_event_ButtonBTNSwitch( lv_event_t * e);
lv_obj_t *ui_ButtonBTNSwitch;
lv_obj_t *ui_LabelConfirm7;
void ui_event_KeyboardOV( lv_event_t * e);
lv_obj_t *ui_KeyboardOV;


// SCREEN: ui_ScreenArm
void ui_ScreenArm_screen_init(void);
lv_obj_t *ui_ScreenArm;
void ui_event_ButtonReturn1( lv_event_t * e);
lv_obj_t *ui_ButtonReturn1;
lv_obj_t *ui_LabelReturn1;
void ui_event_ButtonConfirm( lv_event_t * e);
lv_obj_t *ui_ButtonConfirm;
lv_obj_t *ui_LabelConfirm;
lv_obj_t *ui_DropdownHolder;
void ui_event_TextAreaArmX( lv_event_t * e);
lv_obj_t *ui_TextAreaArmX;
void ui_event_TextAreaArmY( lv_event_t * e);
lv_obj_t *ui_TextAreaArmY;
void ui_event_TextAreaArmZ( lv_event_t * e);
lv_obj_t *ui_TextAreaArmZ;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Label10;
lv_obj_t *ui_SwitchArmTong;
lv_obj_t *ui_LabelTong;
void ui_event_KeyboardArm( lv_event_t * e);
lv_obj_t *ui_KeyboardArm;


// SCREEN: ui_ScreenTask
void ui_ScreenTask_screen_init(void);
lv_obj_t *ui_ScreenTask;
void ui_event_ButtonReturn3( lv_event_t * e);
lv_obj_t *ui_ButtonReturn3;
lv_obj_t *ui_LabelReturn3;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_LabelTaskNum;
void ui_event_ButtonTaskRun( lv_event_t * e);
lv_obj_t *ui_ButtonTaskRun;
lv_obj_t *ui_Label4;
lv_obj_t *ui_LabelFinishTime;


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
void ui_event_ButtonReturn4( lv_event_t * e);
lv_obj_t *ui_ButtonReturn4;
lv_obj_t *ui_LabelReturn4;
lv_obj_t *ui_Label1;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonRGB( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenCFIG, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0, &ui_ScreenCFIG_screen_init);
      SetHighTaskPriority( e );
}
}
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen1, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_Screen1_screen_init);
}
}
void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenTask, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0, &ui_ScreenTask_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      TaskReady( e );
}
}
void ui_event_ButtonArm( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenArm, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0, &ui_ScreenArm_screen_init);
      SetHighTaskPriority( e );
}
}
void ui_event_ButtonReturn2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenMenu, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_ScreenMenu_screen_init);
      SetLowTaskPriority( e );
}
}
void ui_event_ButtonWrite( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      EventOvWrite( e );
}
}
void ui_event_ButtonRead( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      EventOvRead( e );
}
}
void ui_event_ButtonBTN4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      EventBTN4( e );
}
}
void ui_event_ButtonBTN3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      EventBTN3( e );
}
}
void ui_event_ButtonBTN2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      EventBTN2( e );
}
}
void ui_event_ButtonBTN1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      EventBTN1( e );
}
}
void ui_event_TextAreaOV( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      SetKeyBoard( e );
}
}
void ui_event_ButtonBTNSwitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      EventBTNSwitch( e );
}
}
void ui_event_KeyboardOV( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CANCEL) {
      KeyBoardCancel( e );
}
}
void ui_event_ButtonReturn1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenMenu, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_ScreenMenu_screen_init);
      SetLowTaskPriority( e );
}
}
void ui_event_ButtonConfirm( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ArmSetConfirm( e );
}
}
void ui_event_TextAreaArmX( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      SetKeyBoard( e );
}
}
void ui_event_TextAreaArmY( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      SetKeyBoard( e );
}
}
void ui_event_TextAreaArmZ( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      SetKeyBoard( e );
}
}
void ui_event_KeyboardArm( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CANCEL) {
      KeyBoardCancel( e );
}
}
void ui_event_ButtonReturn3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenMenu, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_ScreenMenu_screen_init);
}
}
void ui_event_ButtonTaskRun( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ButtonTaskRun( e );
}
}
void ui_event_ButtonReturn4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ScreenMenu, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0, &ui_ScreenMenu_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_ScreenMenu_screen_init();
ui_ScreenCFIG_screen_init();
ui_ScreenArm_screen_init();
ui_ScreenTask_screen_init();
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ScreenMenu);
}
