// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

#include "stdlib.h"
#include "my_lib/rgb.h"
#include "my_lib/arm.h"
#include "my_lib/route.h"
#include "file_info.h"
#include "steer.h"
#include "step_motor.h"
#include "car_ctrl.h"
#include "my_gui.h"
#include "communication.h"

void TaskReady(lv_event_t * e)
{
    // SetSteerAngle(TurnSteer, TURN_STEER_INIT_ANGLE);
	// ExcuteArmActionArr(ARM_START_POS);
}

void ArmSetConfirm(lv_event_t * e)
{
    float pos[3];
    uint8_t tong_sta;
	uint16_t holder_index;
    const char* str;
    str = lv_textarea_get_text(ui_TextAreaArmX);
    pos[0] = atof(str);
    str = lv_textarea_get_text(ui_TextAreaArmY);
    pos[1] = atof(str);
    str = lv_textarea_get_text(ui_TextAreaArmZ);
    pos[2] = atof(str);

    tong_sta = lv_obj_has_state(ui_SwitchArmTong, LV_STATE_CHECKED);
	holder_index = lv_dropdown_get_selected(ui_DropdownHolder);
    MY_LOG_Print("\r\narm->X[%.1f] Y[%.1f] Z[%.1f] tong[%d] holder[%d]", pos[0], pos[1], pos[2], tong_sta, holder_index);
    SetArmState(pos[0], pos[1], pos[2], tong_sta);
	switch (holder_index)
	{
	case 0:
		SetSteerAngle(TurnSteer, TURN_STEER_INIT_ANGLE);
		break;
	case 1:
		SetSteerAngle(TurnSteer, TURN_STEER_RED);
		break;
	case 2:
		SetSteerAngle(TurnSteer, TURN_STEER_GREEN);
		break;
	case 3:
		SetSteerAngle(TurnSteer, TURN_STEER_BLUE);
		break;
	
	default:
		break;
	}
}

void KeyBoardCancel(lv_event_t * e)
{
	lv_obj_add_flag(ui_KeyboardArm, LV_OBJ_FLAG_HIDDEN); 
	lv_obj_add_flag(ui_KeyboardOV, LV_OBJ_FLAG_HIDDEN); 
}

void SetKeyBoard(lv_event_t * e)
{
    lv_obj_t* obj = lv_event_get_target(e);

	if(obj == ui_TextAreaOV){
		lv_obj_clear_flag(ui_KeyboardOV, LV_OBJ_FLAG_HIDDEN);     /// Flags
	}
	else{
		lv_keyboard_set_textarea(ui_KeyboardArm, obj);
    	lv_obj_clear_flag(ui_KeyboardArm, LV_OBJ_FLAG_HIDDEN);     /// Flags
	}
}

void ButtonTaskRun(lv_event_t * e)
{
	MY_LOG_Print("\r\nexecute task");
    GiveRouteExecuteSem(0);
}


void SetHighTaskPriority(lv_event_t * e)
{
	IsGuiTaskHighPriority(1);
}

void SetLowTaskPriority(lv_event_t * e)
{
	IsGuiTaskHighPriority(0);
}

void EventOvWrite(lv_event_t * e)
{
	const char* str;
    str = lv_textarea_get_text(ui_TextAreaOV);
	uint8_t percent = atoi(str);
	CommunicationTrans(UI_BTN_WRITE_EVENT, &percent, 1);
	MY_LOGI("ov", "send param[%d]", percent);
}

void EventOvRead(lv_event_t * e)
{
	// Your code here
}

void EventBTN4(lv_event_t * e)
{
	MY_LOGI("ui", "btn 4");
	CommunicationTrans(UI_BTN4_EVENT, NULL, 0);
}

void EventBTN3(lv_event_t * e)
{
	MY_LOGI("ui", "btn 3");
	CommunicationTrans(UI_BTN3_EVENT, NULL, 0);
}

void EventBTN2(lv_event_t * e)
{
	MY_LOGI("ui", "btn 2");
	CommunicationTrans(UI_BTN2_EVENT, NULL, 0);
}

void EventBTN1(lv_event_t * e)
{
	MY_LOGI("ui", "btn 1");
	CommunicationTrans(UI_BTN1_EVENT, NULL, 0);
}

void EventBTNSwitch(lv_event_t * e)
{
	static uint8_t ov_disp_en=0;
	ov_disp_en = !ov_disp_en;
	CommunicationTrans(UI_BTN_SWITCH_EVENT, &ov_disp_en, 1);
	MY_LOGI("ov", "ov display sta:%d", ov_disp_en);
}
