// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void SetHighTaskPriority(lv_event_t * e);
void TaskReady(lv_event_t * e);
void SetLowTaskPriority(lv_event_t * e);
void EventOvWrite(lv_event_t * e);
void EventOvRead(lv_event_t * e);
void EventBTN4(lv_event_t * e);
void EventBTN3(lv_event_t * e);
void EventBTN2(lv_event_t * e);
void EventBTN1(lv_event_t * e);
void SetKeyBoard(lv_event_t * e);
void EventBTNSwitch(lv_event_t * e);
void KeyBoardCancel(lv_event_t * e);
void ArmSetConfirm(lv_event_t * e);
void ButtonTaskRun(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
