// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ButtonReturn4 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_ButtonReturn4, lv_pct(15));
lv_obj_set_height( ui_ButtonReturn4, lv_pct(10));
lv_obj_add_flag( ui_ButtonReturn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonReturn4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonReturn4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonReturn4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelReturn4 = lv_label_create(ui_ButtonReturn4);
lv_obj_set_width( ui_LabelReturn4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelReturn4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelReturn4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelReturn4,"<--");
lv_obj_set_style_text_color(ui_LabelReturn4, lv_color_hex(0x100F0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelReturn4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"SWPU Fly team:\n\nteacher:  Cheng Liang\n\ncaptain: Yang Yaoming\n\nmember: Zhou Yuhang, Luo Xinjie\n\nemail: 2819731924@qq.com");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xE53C17), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ButtonReturn4, ui_event_ButtonReturn4, LV_EVENT_ALL, NULL);

}
