// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenArm_screen_init(void)
{
ui_ScreenArm = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenArm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ButtonReturn1 = lv_btn_create(ui_ScreenArm);
lv_obj_set_width( ui_ButtonReturn1, lv_pct(15));
lv_obj_set_height( ui_ButtonReturn1, lv_pct(10));
lv_obj_add_flag( ui_ButtonReturn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonReturn1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonReturn1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonReturn1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelReturn1 = lv_label_create(ui_ButtonReturn1);
lv_obj_set_width( ui_LabelReturn1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelReturn1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelReturn1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelReturn1,"<--");
lv_obj_set_style_text_color(ui_LabelReturn1, lv_color_hex(0x100F0F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelReturn1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonConfirm = lv_btn_create(ui_ScreenArm);
lv_obj_set_width( ui_ButtonConfirm, lv_pct(20));
lv_obj_set_height( ui_ButtonConfirm, lv_pct(15));
lv_obj_set_x( ui_ButtonConfirm, lv_pct(0) );
lv_obj_set_y( ui_ButtonConfirm, lv_pct(-5) );
lv_obj_set_align( ui_ButtonConfirm, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_ButtonConfirm, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonConfirm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonConfirm, lv_color_hex(0xEB1212), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_ButtonConfirm, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_LabelConfirm = lv_label_create(ui_ButtonConfirm);
lv_obj_set_width( ui_LabelConfirm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelConfirm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelConfirm, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelConfirm,"Confirm");

ui_DropdownHolder = lv_dropdown_create(ui_ScreenArm);
lv_dropdown_set_options( ui_DropdownHolder, "init\nred\ngreen\nblue" );
lv_obj_set_width( ui_DropdownHolder, lv_pct(30));
lv_obj_set_height( ui_DropdownHolder, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DropdownHolder, 70 );
lv_obj_set_y( ui_DropdownHolder, 20 );
lv_obj_set_align( ui_DropdownHolder, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DropdownHolder, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags



ui_TextAreaArmX = lv_textarea_create(ui_ScreenArm);
lv_obj_set_width( ui_TextAreaArmX, 55);
lv_obj_set_height( ui_TextAreaArmX, LV_SIZE_CONTENT);   /// 15
lv_obj_set_x( ui_TextAreaArmX, -235 );
lv_obj_set_y( ui_TextAreaArmX, -44 );
lv_obj_set_align( ui_TextAreaArmX, LV_ALIGN_RIGHT_MID );
if ("-0123456789."=="") lv_textarea_set_accepted_chars(ui_TextAreaArmX, NULL);
else lv_textarea_set_accepted_chars(ui_TextAreaArmX, "-0123456789.");
lv_textarea_set_max_length(ui_TextAreaArmX,5);
lv_textarea_set_text(ui_TextAreaArmX,"25");
lv_textarea_set_placeholder_text(ui_TextAreaArmX,"num");
lv_textarea_set_one_line(ui_TextAreaArmX,true);



ui_TextAreaArmY = lv_textarea_create(ui_ScreenArm);
lv_obj_set_width( ui_TextAreaArmY, 55);
lv_obj_set_height( ui_TextAreaArmY, LV_SIZE_CONTENT);   /// 15
lv_obj_set_x( ui_TextAreaArmY, 0 );
lv_obj_set_y( ui_TextAreaArmY, -44 );
lv_obj_set_align( ui_TextAreaArmY, LV_ALIGN_CENTER );
if ("-0123456789."=="") lv_textarea_set_accepted_chars(ui_TextAreaArmY, NULL);
else lv_textarea_set_accepted_chars(ui_TextAreaArmY, "-0123456789.");
lv_textarea_set_max_length(ui_TextAreaArmY,5);
lv_textarea_set_text(ui_TextAreaArmY,"0.0");
lv_textarea_set_placeholder_text(ui_TextAreaArmY,"num");
lv_textarea_set_one_line(ui_TextAreaArmY,true);



ui_TextAreaArmZ = lv_textarea_create(ui_ScreenArm);
lv_obj_set_width( ui_TextAreaArmZ, 55);
lv_obj_set_height( ui_TextAreaArmZ, LV_SIZE_CONTENT);   /// 15
lv_obj_set_x( ui_TextAreaArmZ, 235 );
lv_obj_set_y( ui_TextAreaArmZ, -44 );
lv_obj_set_align( ui_TextAreaArmZ, LV_ALIGN_LEFT_MID );
if ("0123456789."=="") lv_textarea_set_accepted_chars(ui_TextAreaArmZ, NULL);
else lv_textarea_set_accepted_chars(ui_TextAreaArmZ, "0123456789.");
lv_textarea_set_max_length(ui_TextAreaArmZ,5);
lv_textarea_set_text(ui_TextAreaArmZ,"20");
lv_textarea_set_placeholder_text(ui_TextAreaArmZ,"num");
lv_textarea_set_one_line(ui_TextAreaArmZ,true);



ui_Label8 = lv_label_create(ui_ScreenArm);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -103 );
lv_obj_set_y( ui_Label8, -75 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"armX");

ui_Label9 = lv_label_create(ui_ScreenArm);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, 0 );
lv_obj_set_y( ui_Label9, -75 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"armY");

ui_Label10 = lv_label_create(ui_ScreenArm);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, 102 );
lv_obj_set_y( ui_Label10, -75 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"armZ");

ui_SwitchArmTong = lv_switch_create(ui_ScreenArm);
lv_obj_set_width( ui_SwitchArmTong, 50);
lv_obj_set_height( ui_SwitchArmTong, 25);
lv_obj_set_x( ui_SwitchArmTong, -67 );
lv_obj_set_y( ui_SwitchArmTong, -88 );
lv_obj_set_align( ui_SwitchArmTong, LV_ALIGN_BOTTOM_MID );


ui_LabelTong = lv_label_create(ui_ScreenArm);
lv_obj_set_width( ui_LabelTong, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTong, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTong, -119 );
lv_obj_set_y( ui_LabelTong, 132 );
lv_obj_set_align( ui_LabelTong, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_LabelTong,"TONG");

ui_KeyboardArm = lv_keyboard_create(ui_ScreenArm);
lv_keyboard_set_mode(ui_KeyboardArm,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_KeyboardArm, lv_pct(100));
lv_obj_set_height( ui_KeyboardArm, lv_pct(58));
lv_obj_set_align( ui_KeyboardArm, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_KeyboardArm, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_add_event_cb(ui_ButtonReturn1, ui_event_ButtonReturn1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonConfirm, ui_event_ButtonConfirm, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaArmX, ui_event_TextAreaArmX, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaArmY, ui_event_TextAreaArmY, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaArmZ, ui_event_TextAreaArmZ, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_KeyboardArm,ui_TextAreaArmX);
lv_obj_add_event_cb(ui_KeyboardArm, ui_event_KeyboardArm, LV_EVENT_ALL, NULL);

}
